server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://alumhive:alumhive@cluster0.1q3dpcc.mongodb.net/alumhive?appName=Cluster0

# File upload sizes
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# JWT Secrets and Settings
jwt.secret=U2VjcmV0U2VjcmV0U2VjcmV0U2VjcmV0U2VjcmV0U2VjcmV0U2VjcmV0U2VjcmV0U2VjcmV0U2VjcmV0U2VjcmV0U2VjcmV0
jwt.expiration=86400000
